export const DOS_CONTRACT_ADDRESS = process.env.REACT_APP_DOS_CONTRACT_ADDRESS;
export const DB_CONTRACT_ADDRESS = process.env.REACT_APP_DB_CONTRACT_ADDRESS;
export const DOSTOKEN_CONTRACT_ADDRESS = process.env.REACT_APP_DOSTOKEN_CONTRACT_ADDRESS;
export const BLOCK_NUMBER = process.env.REACT_APP_BLOCK_NUMBER;
export const NETWORK = process.env.REACT_APP_NETWORK
