export default {
    'rinkeby': {
        STAKING_CONTRACT_ADDRESS: process.env.REACT_APP_STAKING_CONTRACT_ADDRESS_RINKEBY,
        DBTOKEN_CONTRACT_ADDRESS: process.env.REACT_APP_DBTOKEN_CONTRACT_ADDRESS_RINKEBY,
        DOSTOKEN_CONTRACT_ADDRESS: process.env.REACT_APP_DOSTOKEN_CONTRACT_ADDRESS_RINKEBY,
        BLOCK_NUMBER: process.env.REACT_APP_BLOCK_NUMBER_RINKEBY,
        NETWORK: process.env.REACT_APP_NETWORK_RINKEBY,
        PROVIDER: process.env.REACT_APP_PROVIDER_RINKEBY
    },
    'mainnet': {
        STAKING_CONTRACT_ADDRESS: process.env.REACT_APP_STAKING_CONTRACT_ADDRESS_MAINNET,
        DBTOKEN_CONTRACT_ADDRESS: process.env.REACT_APP_DBTOKEN_CONTRACT_ADDRESS_MAINNET,
        DOSTOKEN_CONTRACT_ADDRESS: process.env.REACT_APP_DOSTOKEN_CONTRACT_ADDRESS_MAINNET,
        BLOCK_NUMBER: process.env.REACT_APP_BLOCK_NUMBER_MAINNET,
        NETWORK: process.env.REACT_APP_NETWORK_MAINNET,
        PROVIDER: process.env.REACT_APP_PROVIDER_MAINNET
    },
    'heco-testnet': {
        STAKING_CONTRACT_ADDRESS: process.env.REACT_APP_STAKING_CONTRACT_ADDRESS_HECOTESTNET,
        DBTOKEN_CONTRACT_ADDRESS: process.env.REACT_APP_DBTOKEN_CONTRACT_ADDRESS_HECOTESTNET,
        DOSTOKEN_CONTRACT_ADDRESS: process.env.REACT_APP_DOSTOKEN_CONTRACT_ADDRESS_HECOTESTNET,
        BLOCK_NUMBER: process.env.REACT_APP_BLOCK_NUMBER_HECOTESTNET,
        NETWORK: process.env.REACT_APP_NETWORK_HECOTESTNET,
        PROVIDER: process.env.REACT_APP_PROVIDER_HECOTESTNET
    },
    'heco': {
        STAKING_CONTRACT_ADDRESS: process.env.REACT_APP_STAKING_CONTRACT_ADDRESS_HECO,
        DBTOKEN_CONTRACT_ADDRESS: process.env.REACT_APP_DBTOKEN_CONTRACT_ADDRESS_HECO,
        DOSTOKEN_CONTRACT_ADDRESS: process.env.REACT_APP_DOSTOKEN_CONTRACT_ADDRESS_HECO,
        BLOCK_NUMBER: process.env.REACT_APP_BLOCK_NUMBER_HECO,
        NETWORK: process.env.REACT_APP_NETWORK_HECO,
        PROVIDER: process.env.REACT_APP_PROVIDER_HECO
    },

}
