export default {
    GLOBAL_CONFIG_CHANGE_OSLM: 'GLOBAL_CONFIG_CHANGE_OSLM',
    GLOBAL_CONFIG_CHANGE_LANG: 'GLOBAL_CONFIG_CHANGE_LANG',
    GLOBAL_CONFIG_SET_LANG: 'GLOBAL_CONFIG_SET_LANG',
    METAMASK_ADDRESS_CHANGE: 'METAMASK_ADDRESS_CHANGE',
    EXPLORER_SEARCH_RESPONSE: 'EXPLORER_SEARCH_RESPONSE',
    EXPLORER_SEARCH_REQUEST: 'EXPLORER_SEARCH_REQUEST',
    CONTRACT_WEB3_CLINET_INIT: 'CONTRACT_WEB3_CLINET_INIT',
    WALLET_ACTIVATE: 'WALLET_ACTIVATE',
    WALLET_DEACTIVATE: 'WALLET_DEACTIVATE',
    CONTRACT_USERADDRESS_CHANGE: 'CONTRACT_USERADDRESS_CHANGE',
    WALLET_NETWORK_CHANGE: 'WALLET_NETWORK_CHANGE'
}
