export default {
    GLOBAL_CONFIG_CHANGE_OSLM: 'GLOBAL_CONFIG_CHANGE_OSLM',
    METAMASK_ADDRESS_CHANGE: 'METAMASK_ADDRESS_CHANGE',
    EXPLORER_SEARCH_RESPONSE: 'EXPLORER_SEARCH_RESPONSE',
    EXPLORER_SEARCH_REQUEST: 'EXPLORER_SEARCH_REQUEST',
    CONTRACT_WEB3_CLINET_INIT: 'CONTRACT_WEB3_CLINET_INIT',
    CONTRACT_METAMASK_LOGIN: 'CONTRACT_METAMASK_LOGIN',
    CONTRACT_METAMASK_LOGOUT: 'CONTRACT_METAMASK_LOGOUT',
    CONTRACT_USERADDRESS_CHANGE: 'CONTRACT_USERADDRESS_CHANGE'
}
